# Set properties of the 'user-store' datasource defined in the 'persistence.xml' file
db-kind-user-store=dev-file
db-url-full-user-store=jdbc:h2:./data/user-store;AUTO_SERVER=TRUE
db-username-user-store=sa
db-password-user-store=password
transaction-xa-enabled-user-store=true